application: planetcloudsave
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /register
  script: register.app

- url: /sync
  script: stateManager.app

libraries:
- name: webapp2
  version: "2.5.2"
